Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 115

Metrics/CyclomaticComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
